# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. 

Vagrant.configure(2) do |config|

  config.vm.box = "devops-controlserver"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder.

  
#  config.vm.synced_folder "../../devops-kungfu", "/home/vagrant/devops-kungfu", create: true

 config.vm.provider "virtualbox" do |v|
   v.name = "devops_controlserver01"
   v.memory = 2048
   v.cpus = 1
   v.gui = true
 end
 config.vm.network "forwarded_port", id: "ssh", guest: 22, host: 10221, auto_correct: true, protocol: "tcp"
 
end
